# Generated by Django 4.2.13 on 2024-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageclassification",
            name="type",
            field=models.CharField(
                choices=[("xray", "xray"), ("dermatology", "dermatology")],
                max_length=20,
            ),
        ),
    ]
