# Generated by Django 4.2.13 on 2024-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medform", "0002_alter_imageclassification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demogrphicscore",
            name="gender",
            field=models.CharField(choices=[("M", "M"), ("F", "F")], max_length=6),
        ),
    ]
