# Generated by Django 4.2.13 on 2024-09-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medform", "0003_alter_demogrphicscore_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="demogrphicscore",
            name="score",
            field=models.FloatField(default=114.23),
            preserve_default=False,
        ),
    ]
