# Generated by Django 4.2.13 on 2024-09-27 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medform", "0004_demogrphicscore_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demogrphicscore",
            old_name="image",
            new_name="model",
        ),
    ]
